/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentação;

import Entidades.CartãoDeCredito;
import Entidades.Usuario;
import Negocio.UsuarioBO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author xulipaxulepa
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {

    public Usuario usuario = null;
    public TelaLogin telalogin = null;
    public TelaInicial telainicial = null;
    private int contador = 0;
    /**
     * Creates new form TelaCadastroUsuario
     *
     * @param telainicial
     */
    public TelaCadastroUsuario(TelaInicial telainicial) {
        initComponents();
        this.telainicial = telainicial;
        this.btnCadastrar.setVisible(false);
        this.btnAlterar.setVisible(true);
        this.lblUserExistente.setVisible(false);
    }

    public TelaCadastroUsuario(TelaLogin telalogin) {
        initComponents();
        this.telalogin = telalogin;
        this.btnAlterar.setVisible(false);
        this.lblUserExistente.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTelaCadastraUsuario = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        lblUserExistente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        pnlTelaCadastraUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblUsername.setText("Username:");

        lblIdade.setText("Idade:");

        lblLogin.setText("Login:");

        lblSenha.setText("Senha:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Editar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        lblUserExistente.setText("(*)");

        javax.swing.GroupLayout pnlTelaCadastraUsuarioLayout = new javax.swing.GroupLayout(pnlTelaCadastraUsuario);
        pnlTelaCadastraUsuario.setLayout(pnlTelaCadastraUsuarioLayout);
        pnlTelaCadastraUsuarioLayout.setHorizontalGroup(
            pnlTelaCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTelaCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                        .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(161, 161, 161))
                    .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUserExistente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlTelaCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                        .addComponent(lblIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(85, 85, 85))))
            .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(lblLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                .addGroup(pnlTelaCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(pnlTelaCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(162, 162, 162))
            .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlTelaCadastraUsuarioLayout.setVerticalGroup(
            pnlTelaCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelaCadastraUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTelaCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(lblIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTelaCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserExistente))
                .addGap(18, 18, 18)
                .addComponent(lblLogin)
                .addGap(18, 18, 18)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSenha)
                .addGap(18, 18, 18)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTelaCadastraUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelaCadastraUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelaCadastraUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        UsuarioBO usuariobo = new UsuarioBO();
        
        if (this.txtUsername.getText().isEmpty() || this.txtIdade.getText().isEmpty() || this.txtLogin.getText().isEmpty() || this.txtSenha.getText().isEmpty()) {
            String mensagem = "Nenhum valor inserido";
            String titulo = "Erro";
            JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
        } else {
            Usuario user = new Usuario();
            this.preencheUsuario(user);

            try {
                usuariobo.criar(user);
                String mensagem = "Cadastro efetuado com sucesso";
                String titulo = "Parabêns";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (SQLException ex) {
                String mensagem = "Houve um erro";
                String titulo = "Erro no banco";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (this.txtUsername.getText().isEmpty() || this.txtIdade.getText().isEmpty() || this.txtLogin.getText().isEmpty() || this.txtSenha.getText().isEmpty()) {
            String mensagem = "Nenhum valor inserido";
            String titulo = "Erro";
            JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
        } else {
            UsuarioBO usuariobo = new UsuarioBO();
            this.usuario = this.telainicial.usuario;
            this.preencheUsuario(this.usuario);
            this.usuario.setUsername(this.txtUsername.getText());
            this.usuario.setIdade(Integer.parseInt(this.txtIdade.getText()));
            this.usuario.setLogin(this.txtLogin.getText());
            this.usuario.setSenha(this.txtSenha.getText());

            try {
                usuariobo.atualizar(this.usuario);
                this.telainicial.preencheDadosTela(this.usuario);
                String mensagem = "Dados atualizados com sucesso";
                String titulo = "Sucesso";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (SQLException ex) {
                String mensagem = "Houve um Erro";
                String titulo = "Erro";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    public void preencheUsuario(Usuario usuario) {
        usuario.setUsername(this.txtUsername.getText());
        int idade = Integer.parseInt(this.txtIdade.getText());
        usuario.setIdade(idade);
        usuario.setLogin(this.txtLogin.getText());
        usuario.setSenha(this.txtSenha.getText());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUserExistente;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlTelaCadastraUsuario;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
