/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentação;

import Entidades.CartãoDeCredito;
import Entidades.Produtora;
import Negocio.CartaoDeCreditoBO;
import Negocio.ProdutoraBO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author xulipaxulepa
 */
public class TelaCadastroProdutora extends javax.swing.JFrame {

    public TelaInicial telainicial = null;
    /**
     * Creates new form TelaCadastroCartao
     */
    public TelaCadastroProdutora(TelaInicial telainicial) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.btnAlterarCartao.setVisible(false);
        this.telainicial = telainicial;
    }
    
    public TelaCadastroProdutora(TelaInicial telainicial,Produtora produtora) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.btnAlterarCartao.setVisible(true);
        this.btnCadastrarCartao.setVisible(false);
        this.telainicial = telainicial;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTelaCadastroCartao = new javax.swing.JPanel();
        lblBanco = new javax.swing.JLabel();
        txtBanco = new javax.swing.JTextField();
        lblNumConta = new javax.swing.JLabel();
        txtNumConta = new javax.swing.JTextField();
        btnCadastrarCartao = new javax.swing.JButton();
        btnAlterarCartao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        pnlTelaCadastroCartao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Produtora", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lblBanco.setText("Nome da produtora:");

        lblNumConta.setText("Localização da produtora:");

        btnCadastrarCartao.setText("Cadastrar Produtora");
        btnCadastrarCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarCartaoActionPerformed(evt);
            }
        });

        btnAlterarCartao.setText("Alterar Produtora");
        btnAlterarCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarCartaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTelaCadastroCartaoLayout = new javax.swing.GroupLayout(pnlTelaCadastroCartao);
        pnlTelaCadastroCartao.setLayout(pnlTelaCadastroCartaoLayout);
        pnlTelaCadastroCartaoLayout.setHorizontalGroup(
            pnlTelaCadastroCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTelaCadastroCartaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTelaCadastroCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTelaCadastroCartaoLayout.createSequentialGroup()
                        .addComponent(lblBanco)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTelaCadastroCartaoLayout.createSequentialGroup()
                        .addComponent(lblNumConta)
                        .addGap(135, 135, 135))))
            .addGroup(pnlTelaCadastroCartaoLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(pnlTelaCadastroCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadastrarCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNumConta)
                    .addComponent(txtBanco))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(pnlTelaCadastroCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTelaCadastroCartaoLayout.createSequentialGroup()
                    .addGap(135, 135, 135)
                    .addComponent(btnAlterarCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(103, 103, 103)))
        );
        pnlTelaCadastroCartaoLayout.setVerticalGroup(
            pnlTelaCadastroCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelaCadastroCartaoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblBanco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNumConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNumConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrarCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(pnlTelaCadastroCartaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTelaCadastroCartaoLayout.createSequentialGroup()
                    .addContainerGap(160, Short.MAX_VALUE)
                    .addComponent(btnAlterarCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelaCadastroCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTelaCadastroCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarCartaoActionPerformed
        if(this.txtBanco.getText().isEmpty() || this.txtNumConta.getText().isEmpty()){
            String mensagem = "Algum valor não digitado";
                String titulo = "Erro";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
        } else{
            Produtora produtora = new Produtora();
            ProdutoraBO produtoraBO = new ProdutoraBO();
            this.preencheCartao(produtora);
            try {
                produtoraBO.criar(produtora);
                String mensagem = "Produtora adicionado com sucesso";
                String titulo = "Sucesso";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (SQLException ex) {
                String mensagem = "Houve um erro";
                String titulo = "Erro";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
            }
            String mensagem = "Produtora cadastrado com sucesso";
                String titulo = "Sucesso";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
        }
        
    }//GEN-LAST:event_btnCadastrarCartaoActionPerformed

    private void btnAlterarCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarCartaoActionPerformed
        if(this.txtBanco.getText().isEmpty() || this.txtNumConta.getText().isEmpty()){
            String mensagem = "Algum valor não digitado";
                String titulo = "Erro";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
        } else{
            Produtora produtora = new Produtora();
            ProdutoraBO produtoraBO = new ProdutoraBO();
            this.preencheCartao(produtora);
            try {
                produtoraBO.atualizar(produtora);
                String mensagem = "Produtora Atualizado com sucesso";
                String titulo = "Sucesso";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (SQLException ex) {
                String mensagem = "Houve um erro";
                String titulo = "Erro";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
            }
            String mensagem = "Produtora Atualizado com sucesso";
                String titulo = "Sucesso";
                JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
        }
    }//GEN-LAST:event_btnAlterarCartaoActionPerformed

    private void preencheCartao(Produtora produtora){
        produtora.setNome(this.txtBanco.getText());
        produtora.setLocalização(this.txtNumConta.getText());
        
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarCartao;
    private javax.swing.JButton btnCadastrarCartao;
    private javax.swing.JLabel lblBanco;
    private javax.swing.JLabel lblNumConta;
    private javax.swing.JPanel pnlTelaCadastroCartao;
    private javax.swing.JTextField txtBanco;
    private javax.swing.JTextField txtNumConta;
    // End of variables declaration//GEN-END:variables
}
